### ISSUE TITLE
Command to download package

### ISSUE THREAD

**Issue by ludwig-austermann** [ThumusLive/utpm#3]
I think it would be neat, if one could download a package from a repo. The features would be:
- automatic installation into package path (maybe into '@utpm' as default dir?)
- usage of exclude option, so people do not have to clone the whole repo
- option to include README, excluded items and so on
- info, update, delete functionalities

**Comment by ThumusLive** [comment]
When someone want to publish their code, they push it on the official repo of packages and then you can import it without using any commands so I'm not sure that can be useful

**Comment by ludwig-austermann** [comment]
I have for instance a package: [din-5008-letter](https://github.com/ludwig-austermann/typst-din-5008-letter), which I prefer not to publish on the official repo (yet). It is not polished yet, functionality is missing, design is not final and I don't want to bloat the repo. I also have some packages, which are private (template in UNI, work) and thus should not be made publicly available.

Anyway, with this functionality, an easy way to install unpublished packages would be achieved, which could be described as an installation method.

**Comment by ThumusLive** [comment]
I see your point and yes it can be really good. I'm adding it at my todo list
